### PR TITLE
Update libraries (libde265 1.0.12, libaom 3.6.1, libheif 1.16.2)

### PR DESCRIPTION
**Pull request by homm**
Depends on https://github.com/carsales/pyheif/pull/86.

Partially based on #85.

### CODE REVIEW

**Comment by ant32bit-carsales** [comment]
Hey @homm are you able to merge the changes from #86 into this?

**Comment by homm** [comment]
Rebase on master

**Review by ant32bit-carsales — APPROVED** [review]
All works great thanks

**Comment by jacobtruman** [comment]
Any chance this could get a version bump?

**Pull request merged**
