### PR TITLE
Read transformations

### PR DESCRIPTION
**Pull request by homm**
Includes and based on #88.

This adopts libheif [transformation read APIs added in 1.16.0](https://github.com/strukturag/libheif/releases/tag/v1.16.0). Unfortunately, added APIs forces to use `ctx` + `item_id` instead of `image_handle` (see [discussion](https://github.com/strukturag/libheif/pull/555#issuecomment-1597100868)), so we have to save ctx reference now.

### CODE REVIEW

**Comment by homm** [comment]
@ant32bit @ant32bit-carsales do you see PRs when I don't mention you? )

**Comment by homm** [comment]
@ant32bit-carsales any chance it will be included in 0.8?

**Comment by ant32bit-carsales** [comment]
Ok rebase it and I'll hold off.

**Comment by homm** [comment]
It doesn't require rebasing.

**Review by ant32bit-carsales — APPROVED** [review]

**Pull request merged**
