### PR TITLE
Step 1: Update dockerfile

### PR DESCRIPTION
**Pull request by homm**
## Make docker build faster
* use curl instead of wget
* libressl, cmake, autoconf, automake, libffi not require building from sources
* skip building extra parts for libde265, libaom, libheif

## Reduce docker image size
* Add .dockerignore
* Remove /build-tools and /build-deps on each layer

## New systems
* Pypy 3.7 & 3.8 wheels added

## Other
* Build libaom from tag, not commit hash
* I had problems with wget related to certs, so I just moved to curl

### CODE REVIEW

**Comment by homm** [comment]
@ant32bit-carsales 

## Step 2: https://github.com/uploadcare/pyheif/pull/5 Run tests in docker before uploading

This will make any changes safer since we can be sure that pyheif works as expected before each release.

## Step 3: https://github.com/uploadcare/pyheif/pull/6 Update dependencies to latest version

Now we finally can update dependencies without breaking anything.

**Comment by homm** [comment]
@ant32bit-carsales 

This PR is the best start point. After that I immediately will send [the second part](https://github.com/uploadcare/pyheif/pull/5) and you will be able to run full builds with tests for all supported Python versions in Docker as simple as this: `docker build --target tested .`

This means that you will be able super easy and reliable test any other PR I sent.

Still waiting for any response.

**Comment by homm** [comment]
> After that I immediately will send the second part

Really sad that you ignored this.

**Comment by ant32bit-carsales** [comment]
Sorry Alexander,

I didn’t realise that you wanted me to wait to do that. I am trying to understand all the parts I have to work on here, too.

From: Alexander Karpinsky ***@***.***>
Date: Tuesday, 16 November 2021 at 6:54 pm
To: carsales/pyheif ***@***.***>
Cc: Anthony Paes ***@***.***>, State change ***@***.***>
Subject: Re: [carsales/pyheif] Step 1: Update dockerfile (PR #59)

After that I immediately will send the second part

Really sad that you ignored this.

**Pull request merged**
